// Auto-derived from plans.config.ts — do not edit this file directly.
// To change plan parameters, edit plans.config.ts instead.
import { PLANS_CONFIG } from './plans.config';

export interface PlanLimits {
  maxStores: number | null;
  maxProductsPerStore: number | null;
  maxMembersPerStore: number | null;
  maxPermanentOrderLinks: number | null;
  hasCategorization: boolean;
  hasStorefrontCustomization: boolean;
  hasApiAccess: boolean;
  hasOrderLinks: boolean;
  hasOrderLinkMessage: boolean;
  hasProductImport: boolean;
}

export interface PlanDiscount {
  percent: number;
  label: string;
  validUntil?: string;
}

export interface PlanDisplay {
  name: string;
  displayName: string;
  priceIdr: number | null;
  effectivePriceIdr: number | null;
  discount: PlanDiscount | null;
  description: string;
  features: string[];
  recommended?: boolean;
  contactEmail?: string;
  limits: PlanLimits;
}

function effectivePrice(priceIdr: number | null, discountPercent?: number): number | null {
  if (priceIdr === null) return null;
  if (!discountPercent) return priceIdr;
  return Math.round(priceIdr * (1 - discountPercent / 100));
}

export const PLAN_LIMITS: Record<string, PlanLimits> = Object.fromEntries(
  Object.entries(PLANS_CONFIG).map(([name, p]) => [
    name,
    {
      maxStores: p.maxStores,
      maxProductsPerStore: p.maxProductsPerStore,
      maxMembersPerStore: p.maxMembersPerStore,
      maxPermanentOrderLinks: p.maxPermanentOrderLinks,
      hasCategorization: p.hasCategorization,
      hasStorefrontCustomization: p.hasStorefrontCustomization,
      hasApiAccess: p.hasApiAccess,
      hasOrderLinks: p.hasOrderLinks,
      hasOrderLinkMessage: p.hasOrderLinkMessage,
      hasProductImport: p.hasProductImport,
    } satisfies PlanLimits,
  ]),
);

/** Effective (post-discount) price used for Midtrans checkout. */
export const PLAN_PRICES: Record<string, number> = Object.fromEntries(
  Object.entries(PLANS_CONFIG)
    .filter(([, p]) => p.priceIdr !== null)
    .map(([name, p]) => [name, effectivePrice(p.priceIdr, p.discount?.percent)!]),
);

export const PLAN_DISPLAY: Record<string, PlanDisplay> = Object.fromEntries(
  Object.entries(PLANS_CONFIG).map(([name, p]) => [
    name,
    {
      name,
      displayName: p.displayName,
      priceIdr: p.priceIdr,
      effectivePriceIdr: effectivePrice(p.priceIdr, p.discount?.percent),
      discount: p.discount ?? null,
      description: p.description,
      features: p.features,
      recommended: p.recommended,
      contactEmail: p.contactEmail,
      limits: PLAN_LIMITS[name],
    } satisfies PlanDisplay,
  ]),
);
