import { Injectable, ForbiddenException, NotFoundException, BadRequestException } from '@nestjs/common';
import { createClerkClient } from '@clerk/clerk-sdk-node';
import { SupabaseService } from '../common/supabase/supabase.service';
import { StoresService } from '../stores/stores.service';
import { EmailService } from '../email/email.service';
import { SubscriptionsService } from '../subscriptions/subscriptions.service';
import { InviteMemberDto } from './dto/invite-member.dto';

@Injectable()
export class MembersService {
  private readonly clerk = createClerkClient({ secretKey: process.env.CLERK_SECRET_KEY });

  constructor(
    private readonly supabase: SupabaseService,
    private readonly stores: StoresService,
    private readonly emailService: EmailService,
    private readonly subscriptions: SubscriptionsService,
  ) {}

  async list(storeId: string, userId: string) {
    await this.requireMembership(storeId, userId);

    const { data, error } = await this.supabase.client
      .from('store_members')
      .select('id, user_id, email, role, created_at, invitation_status')
      .eq('store_id', storeId);

    if (error) throw new Error(error.message);

    return (data as any[]).map((m) => ({
      id: m.id,
      email: m.email,
      role: m.role,
      invitationStatus: m.invitation_status ?? 'accepted',
      ...(m.user_id ? { joinedAt: m.created_at } : { invitedAt: m.created_at }),
    }));
  }

  async invite(storeId: string, dto: InviteMemberDto, userId: string) {
    await this.requireOwner(storeId, userId);
    await this.subscriptions.checkMemberLimit(storeId);

    // Prevent duplicate invitations
    const { data: existing } = await this.supabase.client
      .from('store_members')
      .select('id')
      .eq('store_id', storeId)
      .eq('email', dto.email)
      .maybeSingle();

    if (existing) {
      throw new BadRequestException('Email ini sudah terdaftar sebagai anggota atau sudah diundang');
    }

    // Get inviter name
    let inviterName = 'Pemilik toko';
    try {
      const inviter = await this.clerk.users.getUser(userId);
      inviterName =
        [inviter.firstName, inviter.lastName].filter(Boolean).join(' ') ||
        inviter.emailAddresses[0]?.emailAddress ||
        'Pemilik toko';
    } catch {
      // use default
    }

    // Get store name
    const { data: store } = await this.supabase.client
      .from('stores')
      .select('name')
      .eq('id', storeId)
      .single();

    const storeName = (store as any)?.name ?? 'Toko';

    // Insert with pending_email status — invitation_token is auto-generated by the DB default
    const { data, error } = await this.supabase.client
      .from('store_members')
      .insert({
        store_id: storeId,
        user_id: null,
        email: dto.email,
        role: dto.role,
        invitation_status: 'pending_email',
      })
      .select('invitation_token')
      .single();

    if (error) throw new Error(error.message);

    const token = (data as any).invitation_token;
    const frontendUrl = process.env.FRONTEND_URL ?? 'http://localhost:3000';
    const acceptUrl = `${frontendUrl}/invite/accept?token=${token}`;

    try {
      await this.emailService.sendInvitation(dto.email, storeName, inviterName, acceptUrl);
    } catch (e) {
      // Email failure is non-fatal; the invite row exists and can be re-sent
      console.error('Failed to send invitation email:', e);
    }

    return { success: true };
  }

  async remove(storeId: string, memberId: string, userId: string) {
    await this.requireOwner(storeId, userId);

    const { data: target } = await this.supabase.client
      .from('store_members')
      .select('role')
      .eq('id', memberId)
      .eq('store_id', storeId)
      .single();

    if ((target as any)?.role === 'owner') {
      throw new ForbiddenException('Cannot remove the store owner. Transfer ownership first.');
    }

    const { error, count } = await this.supabase.client
      .from('store_members')
      .delete({ count: 'exact' })
      .eq('id', memberId)
      .eq('store_id', storeId);

    if (error) throw new Error(error.message);
    if (!count) throw new NotFoundException('Member not found');
    return { success: true };
  }

  async transferOwnership(storeId: string, targetMemberId: string, userId: string) {
    await this.requireOwner(storeId, userId);

    const { data: target, error: targetErr } = await this.supabase.client
      .from('store_members')
      .select('id, user_id, role')
      .eq('id', targetMemberId)
      .eq('store_id', storeId)
      .single();

    if (targetErr || !target) throw new NotFoundException('Member not found');
    if (!(target as any).user_id) throw new ForbiddenException('Cannot transfer to a pending invite');

    const { data: currentOwner } = await this.supabase.client
      .from('store_members')
      .select('id')
      .eq('store_id', storeId)
      .eq('user_id', userId)
      .single();

    // Demote current owner first; if promoting the target then fails, revert.
    const { error: demoteErr } = await this.supabase.client
      .from('store_members')
      .update({ role: 'admin' })
      .eq('id', (currentOwner as any).id);

    if (demoteErr) throw new Error(demoteErr.message);

    const { error: promoteErr } = await this.supabase.client
      .from('store_members')
      .update({ role: 'owner' })
      .eq('id', targetMemberId);

    if (promoteErr) {
      // Revert demotion to avoid a store with no owner
      await this.supabase.client
        .from('store_members')
        .update({ role: 'owner' })
        .eq('id', (currentOwner as any).id);
      throw new Error(promoteErr.message);
    }

    return { success: true };
  }

  private async requireMembership(storeId: string, userId: string) {
    const role = await this.stores.getUserRole(storeId, userId);
    if (!role) throw new ForbiddenException();
  }

  private async requireOwner(storeId: string, userId: string) {
    const role = await this.stores.getUserRole(storeId, userId);
    if (role !== 'owner') throw new ForbiddenException();
  }
}
