[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "nft"

# Forward all requests to the NestJS serverless function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
