/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/credits` | `/credits`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/subscriptions` | `/subscriptions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/vouchers` | `/vouchers`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/credits` | `/credits`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/subscriptions` | `/subscriptions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/vouchers` | `/vouchers`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/credits${`?${string}` | `#${string}` | ''}` | `/credits${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/subscriptions${`?${string}` | `#${string}` | ''}` | `/subscriptions${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/vouchers${`?${string}` | `#${string}` | ''}` | `/vouchers${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/credits` | `/credits`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/subscriptions` | `/subscriptions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/vouchers` | `/vouchers`; params?: Router.UnknownInputParams; };
    }
  }
}
